import uuid
from sqlalchemy import (
    Column, String, DateTime, Date, BigInteger, Index, UniqueConstraint, text
)
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import declarative_base
from sqlalchemy.sql import func

Base = declarative_base()


class TenancyEvent(Base):
    __tablename__ = "tenancy_events"

    # Primary key using UUID - keeps things consistent with other tables.
    # server_default ensures a UUID is generated by Postgres even on raw
    # SQL / bulk inserts that bypass the ORM. Requires the pgcrypto
    # extension: CREATE EXTENSION IF NOT EXISTS pgcrypto;
    event_id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        nullable=False,
    )

    # Which tenancy this belongs to
    tenancy_id = Column(UUID(as_uuid=True), nullable=False)

    # Sequence number for ordering - don't touch this without checking deps.
    # NOTE: this is application-assigned, not DB-generated. Under concurrent
    # writes for the same tenancy_id, two processes can race to compute the
    # same "next" value. The unique constraint below will correctly reject
    # the second insert - callers MUST catch that IntegrityError and retry
    # with a freshly computed sequence_number, rather than assuming success.
    # For stronger guarantees, consider a Postgres sequence per tenancy or
    # an advisory lock (pg_advisory_xact_lock) around the read-then-insert.
    sequence_number = Column(BigInteger, nullable=False)

    # Event type (RENT_PAID, LEASE_SIGNED, etc)
    event_type = Column(String(64), nullable=False, index=True)

    effective_date = Column(Date, nullable=False, index=True)

    # Timestamp - always UTC. server_default makes this authoritative at
    # the DB level regardless of which client/path performs the insert.
    recorded_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # Payload data - can get large
    payload = Column(JSONB, nullable=False, default=dict)

    # Metadata field (renamed from 'metadata' to avoid SQLAlchemy conflicts)
    event_metadata = Column(JSONB, nullable=False, default=dict)

    __table_args__ = (
        UniqueConstraint(
            "tenancy_id", "sequence_number", name="uq_tenancy_sequence"
        ),
        # Composite index covers lookups on tenancy_id alone too (leftmost
        # prefix), so a standalone index on tenancy_id was redundant.
        Index("ix_tenancy_effective", "tenancy_id", "effective_date"),
    )